#!/bin/sh

set -e # Exit on error

case "$1" in
  start)
    echo "Loading kernel modules for ldd functionality..."
    /etc/init.d/ldd3_scripts/scull_load
    /etc/init.d/ldd3_scripts/module_load faulty
    modprobe hello
    ;;
  stop)
    echo "Unloading ldd kernel modules..."
    /etc/init.d/ldd3_scripts/scull_unload
    /etc/init.d/ldd3_scripts/module_unload faulty
    rmmod hello
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
